# Generated by Django 4.2 on 2023-08-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_alter_question_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='task_type',
            field=models.IntegerField(default=0),
        ),
    ]
