# Generated by Django 4.2 on 2023-05-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DANPOLZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(help_text='Enter your Nickname', max_length=50, verbose_name='Nickname')),
            ],
        ),
    ]
